version: "3.9"

services:
  user-service:
    build:
      context: src/user-service
      target: user-service
    environment:
      ENV: local
      MAVEN_CONFIG: /root/.m2
      DB_JDBC_URL: 'jdbc:postgresql://db:5432/postgres'
      DB_USERNAME: postgres
      DB_PASSWORD: super
      DB_CHANGELOG_FILE: 'db/db.changelog-root.yml'
    expose:
      - 80
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    volumes:
      - ./src/user-service:/usr/src/app
      - ${HOME}/.m2/repository:/root/.m2/repository

  db-migration:
    build:
      context: src/db-migration-service
      target: db-migration-service
    environment:
      ENV: local
      MAVEN_CONFIG: /root/.m2
      DB_JDBC_URL: 'jdbc:postgresql://db:5432/postgres'
      DB_USERNAME: postgres
      DB_PASSWORD: super
      DB_CHANGELOG_FILE: 'db/db.changelog-root.yml'
    expose:
      - 80
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    volumes:
      - ./src/db-migration-service:/usr/src/app
      - ${HOME}/.m2/repository:/root/.m2/repository

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super
      POSTGRES_DB: postgres
    image: postgres:13
    ports:
      - 5432:5432
    # volumes:
    #   - postgres:/var/lib/postgresql/data

# volumes:
#   postgres:
